# Generated by Django 3.2.16 on 2023-01-29 06:38

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=28, max_length=40, prefix='KWS_CRD_', primary_key=True, serialize=False),
        ),
    ]
